name: Build and deploy docs

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
          
      - name: Setup repository
        uses: ./.github/workflows/actions/setup-repository

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Build libraries
        run: pnpm build

      - name: Build docs
        run: pnpm docs:build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
